jobs:
  build:
    docker:
      - image: cimg/base:stable # primary container will run the latest, production-ready base image
    steps:
      - run:
          command: |
            set -x
            getconf _NPROCESSORS_ONLN
            env
            cat /proc/cpuinfo
            cat /proc/meminfo
            cat /proc/self/cgroup
            cat /proc/self/status
