jobs:
  test:
    docker:
      - image: cimg/base:stable # primary container will run the latest, production-ready base image
    steps:
      - run:
          command: |
            cat /proc/cpuinfo
            cat /proc/meminfo
            cat /proc/self/cgroup
            cat /proc/self/status
